services:
  db:
    image: postgres:latest
    container_name: task_db_container
    restart: always
    env_file:
      - ./be/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build: ./be
    container_name: task_be_container
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./be/.env
    depends_on:
      - db
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm start"
  
  frontend:
    build: ./fe
    container_name: task_fe_container
    restart: always
    ports:
      - "5173:80"
    env_file:
      - ./fe/.env
    depends_on:
      - backend

volumes:
  pgdata:
